const fs = require('fs');
const path = require('path');

const REFERENCES_DIR = path.join(__dirname, 'references');
const OUTPUT_FILE = path.join(__dirname, 'app', 'lib', 'cdc-data.ts');

const FILES = {
    bmi: 'bmiagerev.csv',
    height: 'statage.csv',
    weight: 'wtage.csv'
};

function parseCSV(filePath) {
    const content = fs.readFileSync(filePath, 'utf8');
    const lines = content.trim().split('\n');
    const data = { male: [], female: [] };

    // Skip header
    for (let i = 1; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;
        const parts = line.split(',');

        const sex = parts[0]; // 1 = male, 2 = female
        const ageMonths = parseFloat(parts[1]);
        const l = parseFloat(parts[2]);
        const m = parseFloat(parts[3]);
        const s = parseFloat(parts[4]);

        const point = {
            age_months: ageMonths,
            L: l,
            M: m,
            S: s
        };

        if (sex === '1') {
            data.male.push(point);
        } else if (sex === '2') {
            data.female.push(point);
        }
    }
    return data;
}

function generateFile() {
    console.log('Generating CDC data...');

    const weightData = parseCSV(path.join(REFERENCES_DIR, FILES.weight));
    const heightData = parseCSV(path.join(REFERENCES_DIR, FILES.height));
    const bmiData = parseCSV(path.join(REFERENCES_DIR, FILES.bmi));

    const content = `// This file is auto-generated by generate_cdc_standards.js
// Do not edit manually.
// Source: CDC Growth Charts (2000)

export interface LMSDataPoint {
  age_months: number;
  L: number;
  M: number;
  S: number;
}

export const CDC_WEIGHT_DATA = {
  male: ${JSON.stringify(weightData.male, null, 2)} as LMSDataPoint[],
  female: ${JSON.stringify(weightData.female, null, 2)} as LMSDataPoint[]
};

export const CDC_HEIGHT_DATA = {
  male: ${JSON.stringify(heightData.male, null, 2)} as LMSDataPoint[],
  female: ${JSON.stringify(heightData.female, null, 2)} as LMSDataPoint[]
};

export const CDC_BMI_DATA = {
  male: ${JSON.stringify(bmiData.male, null, 2)} as LMSDataPoint[],
  female: ${JSON.stringify(bmiData.female, null, 2)} as LMSDataPoint[]
};
`;

    fs.writeFileSync(OUTPUT_FILE, content);
    console.log(`Generated ${OUTPUT_FILE}`);
}

generateFile();
